"use client"

export type Language = "en" | "hi" | "bn" | "gu" | "ta" | "te" | "mr" | "kn" | "ml" | "pa"

export const languages: { code: Language; name: string; native: string }[] = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
]

type TranslationKeys = {
  // Common
  back: string
  continue: string
  confirm: string
  cancel: string
  loading: string
  
  // Intro
  introTitle: string
  introSubtitle: string
  beginJourney: string
  
  // Language selection
  selectLanguage: string
  chooseLanguage: string
  
  // Login
  enterPhone: string
  phoneNumber: string
  sendOtp: string
  enterOtp: string
  verifyOtp: string
  resendOtp: string
  resendIn: string
  
  // Name
  enterName: string
  yourName: string
  welcomeUser: string
  
  // Dashboard
  chooseRole: string
  roleQuestion: string
  buyer: string
  buyerDesc: string
  grocer: string
  grocerDesc: string
  xpEarned: string
  level: string
  
  // Buyer
  chooseQuest: string
  selectProduce: string
  climactericFruits: string
  climactericDesc: string
  nonClimactericFruits: string
  nonClimactericDesc: string
  browseCollection: string
  viewMarketplace: string
  addToCart: string
  buyNow: string
  freshness: string
  shelfLife: string
  price: string
  
  // Grocer
  grocerGuild: string
  uploadPhotos: string
  uploadDesc: string
  frontView: string
  sideView: string
  topView: string
  closeUp: string
  analyzeAI: string
  detectionResults: string
  detectedFruit: string
  category: string
  freshnessScore: string
  confirmListing: string
  yourListings: string
  noListings: string
  
  // Recommendations
  recommendedUses: string
  faceMask: string
  juice: string
  smoothie: string
  cooking: string
  compost: string
  
  // Purchase
  purchaseSuccess: string
  grocerDetails: string
  grocerName: string
  grocerPhone: string
  grocerLocation: string
  pickupLocation: string
}

const translations: Record<Language, TranslationKeys> = {
  en: {
    back: "Back",
    continue: "Continue",
    confirm: "Confirm",
    cancel: "Cancel",
    loading: "Loading...",
    introTitle: "TerraLoop",
    introSubtitle: "Fresh Produce, Magical Experience",
    beginJourney: "Begin Your Journey",
    selectLanguage: "Select Language",
    chooseLanguage: "Choose your preferred language",
    enterPhone: "Enter your phone number",
    phoneNumber: "Phone Number",
    sendOtp: "Send OTP",
    enterOtp: "Enter OTP",
    verifyOtp: "Verify OTP",
    resendOtp: "Resend OTP",
    resendIn: "Resend in",
    enterName: "Enter your name",
    yourName: "Your Name",
    welcomeUser: "Welcome",
    chooseRole: "Choose Your Path",
    roleQuestion: "Are you a buyer or grocer?",
    buyer: "Buyer",
    buyerDesc: "Browse and purchase fresh produce from local grocers",
    grocer: "Grocer",
    grocerDesc: "List your produce and reach more customers",
    xpEarned: "XP Earned",
    level: "Level",
    chooseQuest: "Choose Your Quest",
    selectProduce: "Select the type of produce you seek",
    climactericFruits: "Climacteric Fruits",
    climactericDesc: "Fruits that continue ripening after harvest",
    nonClimactericFruits: "Non-Climacteric Fruits",
    nonClimactericDesc: "Fruits picked at peak ripeness",
    browseCollection: "Browse Collection",
    viewMarketplace: "View in Marketplace",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    freshness: "Freshness",
    shelfLife: "Shelf Life",
    price: "Price",
    grocerGuild: "Grocer's Guild",
    uploadPhotos: "Upload 4 Photos",
    uploadDesc: "Capture from different angles for accurate AI analysis",
    frontView: "Front View",
    sideView: "Side View",
    topView: "Top View",
    closeUp: "Close-up",
    analyzeAI: "Analyze with AI",
    detectionResults: "AI Detection Results",
    detectedFruit: "Detected Fruit",
    category: "Category",
    freshnessScore: "Freshness Score",
    confirmListing: "Confirm & List",
    yourListings: "Your Listings",
    noListings: "No produce listed yet",
    recommendedUses: "Recommended Uses",
    faceMask: "Face Mask",
    juice: "Fresh Juice",
    smoothie: "Smoothie",
    cooking: "Cooking",
    compost: "Compost",
    purchaseSuccess: "Purchase Successful!",
    grocerDetails: "Grocer Details",
    grocerName: "Grocer Name",
    grocerPhone: "Phone",
    grocerLocation: "Pickup Location",
    pickupLocation: "Pickup Location",
  },
  hi: {
    back: "वापस",
    continue: "जारी रखें",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    loading: "लोड हो रहा है...",
    introTitle: "टेरालूप",
    introSubtitle: "ताज़ी सब्ज़ियाँ, जादुई अनुभव",
    beginJourney: "अपनी यात्रा शुरू करें",
    selectLanguage: "भाषा चुनें",
    chooseLanguage: "अपनी पसंदीदा भाषा चुनें",
    enterPhone: "अपना फ़ोन नंबर दर्ज करें",
    phoneNumber: "फ़ोन नंबर",
    sendOtp: "OTP भेजें",
    enterOtp: "OTP दर्ज करें",
    verifyOtp: "OTP सत्यापित करें",
    resendOtp: "OTP दोबारा भेजें",
    resendIn: "दोबारा भेजें",
    enterName: "अपना नाम दर्ज करें",
    yourName: "आपका नाम",
    welcomeUser: "स्वागत है",
    chooseRole: "अपना रास्ता चुनें",
    roleQuestion: "आप खरीदार हैं या दुकानदार?",
    buyer: "खरीदार",
    buyerDesc: "स्थानीय दुकानदारों से ताज़ी सब्ज़ियाँ खरीदें",
    grocer: "दुकानदार",
    grocerDesc: "अपनी सब्ज़ियाँ सूचीबद्ध करें और अधिक ग्राहकों तक पहुँचें",
    xpEarned: "XP अर्जित",
    level: "स्तर",
    chooseQuest: "अपनी खोज चुनें",
    selectProduce: "उस प्रकार की सब्ज़ी चुनें जो आप चाहते हैं",
    climactericFruits: "क्लाइमेक्टेरिक फल",
    climactericDesc: "फल जो तोड़ने के बाद भी पकते रहते हैं",
    nonClimactericFruits: "नॉन-क्लाइमेक्टेरिक फल",
    nonClimactericDesc: "पूर्ण पके हुए फल",
    browseCollection: "संग्रह देखें",
    viewMarketplace: "मार्केटप्लेस में देखें",
    addToCart: "कार्ट में डालें",
    buyNow: "अभी खरीदें",
    freshness: "ताज़गी",
    shelfLife: "शेल्फ लाइफ",
    price: "कीमत",
    grocerGuild: "दुकानदार गिल्ड",
    uploadPhotos: "4 फ़ोटो अपलोड करें",
    uploadDesc: "सटीक AI विश्लेषण के लिए विभिन्न कोणों से कैप्चर करें",
    frontView: "सामने का दृश्य",
    sideView: "साइड व्यू",
    topView: "टॉप व्यू",
    closeUp: "क्लोज़-अप",
    analyzeAI: "AI से विश्लेषण करें",
    detectionResults: "AI पहचान परिणाम",
    detectedFruit: "पहचाना गया फल",
    category: "श्रेणी",
    freshnessScore: "ताज़गी स्कोर",
    confirmListing: "पुष्टि करें और सूचीबद्ध करें",
    yourListings: "आपकी सूचियाँ",
    noListings: "अभी तक कोई सब्ज़ी सूचीबद्ध नहीं है",
    recommendedUses: "अनुशंसित उपयोग",
    faceMask: "फेस मास्क",
    juice: "ताज़ा जूस",
    smoothie: "स्मूदी",
    cooking: "खाना पकाना",
    compost: "खाद",
    purchaseSuccess: "खरीदारी सफल!",
    grocerDetails: "दुकानदार विवरण",
    grocerName: "दुकानदार का नाम",
    grocerPhone: "फ़ोन",
    grocerLocation: "पिकअप स्थान",
    pickupLocation: "पिकअप स्थान",
  },
  bn: {
    back: "পেছনে",
    continue: "চালিয়ে যান",
    confirm: "নিশ্চিত করুন",
    cancel: "বাতিল",
    loading: "লোড হচ্ছে...",
    introTitle: "টেরালুপ",
    introSubtitle: "তাজা ফল, জাদুকরী অভিজ্ঞতা",
    beginJourney: "আপনার যাত্রা শুরু করুন",
    selectLanguage: "ভাষা নির্বাচন করুন",
    chooseLanguage: "আপনার পছন্দের ভাষা বেছে নিন",
    enterPhone: "আপনার ফোন নম্বর লিখুন",
    phoneNumber: "ফোন নম্বর",
    sendOtp: "OTP পাঠান",
    enterOtp: "OTP লিখুন",
    verifyOtp: "OTP যাচাই করুন",
    resendOtp: "OTP আবার পাঠান",
    resendIn: "আবার পাঠান",
    enterName: "আপনার নাম লিখুন",
    yourName: "আপনার নাম",
    welcomeUser: "স্বাগতম",
    chooseRole: "আপনার পথ বেছে নিন",
    roleQuestion: "আপনি কি ক্রেতা না বিক্রেতা?",
    buyer: "ক্রেতা",
    buyerDesc: "স্থানীয় বিক্রেতাদের কাছ থেকে তাজা ফল কিনুন",
    grocer: "বিক্রেতা",
    grocerDesc: "আপনার ফল তালিকাভুক্ত করুন",
    xpEarned: "XP অর্জিত",
    level: "স্তর",
    chooseQuest: "আপনার অনুসন্ধান বেছে নিন",
    selectProduce: "আপনি যে ধরনের ফল চান তা নির্বাচন করুন",
    climactericFruits: "ক্লাইমেক্টেরিক ফল",
    climactericDesc: "ফল যা সংগ্রহের পরেও পাকতে থাকে",
    nonClimactericFruits: "নন-ক্লাইমেক্টেরিক ফল",
    nonClimactericDesc: "সম্পূর্ণ পাকা ফল",
    browseCollection: "সংগ্রহ দেখুন",
    viewMarketplace: "মার্কেটপ্লেসে দেখুন",
    addToCart: "কার্টে যোগ করুন",
    buyNow: "এখনই কিনুন",
    freshness: "তাজাতা",
    shelfLife: "শেলফ লাইফ",
    price: "দাম",
    grocerGuild: "বিক্রেতা গিল্ড",
    uploadPhotos: "4টি ছবি আপলোড করুন",
    uploadDesc: "সঠিক AI বিশ্লেষণের জন্য বিভিন্ন কোণ থেকে ক্যাপচার করুন",
    frontView: "সামনের দৃশ্য",
    sideView: "পাশের দৃশ্য",
    topView: "উপরের দৃশ্য",
    closeUp: "ক্লোজ-আপ",
    analyzeAI: "AI দিয়ে বিশ্লেষণ করুন",
    detectionResults: "AI সনাক্তকরণ ফলাফল",
    detectedFruit: "সনাক্ত করা ফল",
    category: "বিভাগ",
    freshnessScore: "তাজাতা স্কোর",
    confirmListing: "নিশ্চিত করুন এবং তালিকাভুক্ত করুন",
    yourListings: "আপনার তালিকা",
    noListings: "এখনও কোনো ফল তালিকাভুক্ত করা হয়নি",
    recommendedUses: "প্রস্তাবিত ব্যবহার",
    faceMask: "ফেস মাস্ক",
    juice: "তাজা জুস",
    smoothie: "স্মুদি",
    cooking: "রান্না",
    compost: "সার",
    purchaseSuccess: "ক্রয় সফল!",
    grocerDetails: "বিক্রেতার বিবরণ",
    grocerName: "বিক্রেতার নাম",
    grocerPhone: "ফোন",
    grocerLocation: "পিকআপ অবস্থান",
    pickupLocation: "পিকআপ অবস্থান",
  },
  gu: {
    back: "પાછા",
    continue: "ચાલુ રાખો",
    confirm: "પુષ્ટિ કરો",
    cancel: "રદ કરો",
    loading: "લોડ થઈ રહ્યું છે...",
    introTitle: "ટેરાલૂપ",
    introSubtitle: "તાજા ફળો, જાદુઈ અનુભવ",
    beginJourney: "તમારી યાત્રા શરૂ કરો",
    selectLanguage: "ભાષા પસંદ કરો",
    chooseLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    enterPhone: "તમારો ફોન નંબર દાખલ કરો",
    phoneNumber: "ફોન નંબર",
    sendOtp: "OTP મોકલો",
    enterOtp: "OTP દાખલ કરો",
    verifyOtp: "OTP ચકાસો",
    resendOtp: "OTP ફરીથી મોકલો",
    resendIn: "ફરીથી મોકલો",
    enterName: "તમારું નામ દાખલ કરો",
    yourName: "તમારું નામ",
    welcomeUser: "સ્વાગત છે",
    chooseRole: "તમારો રસ્તો પસંદ કરો",
    roleQuestion: "તમે ખરીદનાર છો કે વેચનાર?",
    buyer: "ખરીદનાર",
    buyerDesc: "સ્થાનિક વેચનારો પાસેથી તાજા ફળો ખરીદો",
    grocer: "વેચનાર",
    grocerDesc: "તમારા ફળોની યાદી બનાવો",
    xpEarned: "XP કમાયા",
    level: "સ્તર",
    chooseQuest: "તમારી શોધ પસંદ કરો",
    selectProduce: "તમે જે પ્રકારના ફળો શોધો છો તે પસંદ કરો",
    climactericFruits: "ક્લાઇમેક્ટેરિક ફળો",
    climactericDesc: "ફળો જે લણણી પછી પણ પાકે છે",
    nonClimactericFruits: "નોન-ક્લાઇમેક્ટેરિક ફળો",
    nonClimactericDesc: "સંપૂર્ણ પાકેલા ફળો",
    browseCollection: "સંગ્રહ જુઓ",
    viewMarketplace: "માર્કેટપ્લેસમાં જુઓ",
    addToCart: "કાર્ટમાં ઉમેરો",
    buyNow: "હમણાં ખરીદો",
    freshness: "તાજગી",
    shelfLife: "શેલ્ફ લાઇફ",
    price: "કિંમત",
    grocerGuild: "વેચનાર ગિલ્ડ",
    uploadPhotos: "4 ફોટા અપલોડ કરો",
    uploadDesc: "સચોટ AI વિશ્લેષણ માટે વિવિધ ખૂણાઓથી કેપ્ચર કરો",
    frontView: "આગળનો દૃશ્ય",
    sideView: "બાજુનો દૃશ્ય",
    topView: "ઉપરનો દૃશ્ય",
    closeUp: "ક્લોઝ-અપ",
    analyzeAI: "AI સાથે વિશ્લેષણ કરો",
    detectionResults: "AI શોધ પરિણામો",
    detectedFruit: "શોધાયેલ ફળ",
    category: "શ્રેણી",
    freshnessScore: "તાજગી સ્કોર",
    confirmListing: "પુષ્ટિ કરો અને યાદી બનાવો",
    yourListings: "તમારી યાદીઓ",
    noListings: "હજુ સુધી કોઈ ફળ સૂચિબદ્ધ નથી",
    recommendedUses: "ભલામણ કરેલ ઉપયોગો",
    faceMask: "ફેસ માસ્ક",
    juice: "તાજો રસ",
    smoothie: "સ્મૂધી",
    cooking: "રસોઈ",
    compost: "ખાતર",
    purchaseSuccess: "ખરીદી સફળ!",
    grocerDetails: "વેચનારની વિગતો",
    grocerName: "વેચનારનું નામ",
    grocerPhone: "ફોન",
    grocerLocation: "પિકઅપ સ્થાન",
    pickupLocation: "પિકઅપ સ્થાન",
  },
  ta: {
    back: "பின்",
    continue: "தொடரவும்",
    confirm: "உறுதிப்படுத்து",
    cancel: "ரத்து",
    loading: "ஏற்றுகிறது...",
    introTitle: "டெர்ராலூப்",
    introSubtitle: "புதிய பழங்கள், மந்திர அனுபவம்",
    beginJourney: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    chooseLanguage: "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    enterPhone: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    phoneNumber: "தொலைபேசி எண்",
    sendOtp: "OTP அனுப்பு",
    enterOtp: "OTP உள்ளிடவும்",
    verifyOtp: "OTP சரிபார்க்கவும்",
    resendOtp: "OTP மீண்டும் அனுப்பு",
    resendIn: "மீண்டும் அனுப்பு",
    enterName: "உங்கள் பெயரை உள்ளிடவும்",
    yourName: "உங்கள் பெயர்",
    welcomeUser: "வரவேற்கிறோம்",
    chooseRole: "உங்கள் பாதையைத் தேர்ந்தெடுக்கவும்",
    roleQuestion: "நீங்கள் வாங்குபவரா அல்லது விற்பனையாளரா?",
    buyer: "வாங்குபவர்",
    buyerDesc: "உள்ளூர் விற்பனையாளர்களிடமிருந்து புதிய பழங்களை வாங்குங்கள்",
    grocer: "விற்பனையாளர்",
    grocerDesc: "உங்கள் பழங்களைப் பட்டியலிடுங்கள்",
    xpEarned: "XP சம்பாதித்தது",
    level: "நிலை",
    chooseQuest: "உங்கள் தேடலைத் தேர்ந்தெடுக்கவும்",
    selectProduce: "நீங்கள் தேடும் பழ வகையைத் தேர்ந்தெடுக்கவும்",
    climactericFruits: "க்ளைமாக்டெரிக் பழங்கள்",
    climactericDesc: "அறுவடைக்குப் பிறகும் பழுக்கும் பழங்கள்",
    nonClimactericFruits: "நான்-க்ளைமாக்டெரிக் பழங்கள்",
    nonClimactericDesc: "முழுமையாக பழுத்த பழங்கள்",
    browseCollection: "சேகரிப்பைக் காண்க",
    viewMarketplace: "சந்தையில் காண்க",
    addToCart: "கார்ட்டில் சேர்",
    buyNow: "இப்போது வாங்கு",
    freshness: "புத்துணர்ச்சி",
    shelfLife: "அடுக்கு ஆயுள்",
    price: "விலை",
    grocerGuild: "விற்பனையாளர் கில்ட்",
    uploadPhotos: "4 புகைப்படங்களைப் பதிவேற்றவும்",
    uploadDesc: "துல்லியமான AI பகுப்பாய்விற்கு வெவ்வேறு கோணங்களில் படம் எடுக்கவும்",
    frontView: "முன் காட்சி",
    sideView: "பக்க காட்சி",
    topView: "மேல் காட்சி",
    closeUp: "நெருக்கமான காட்சி",
    analyzeAI: "AI உடன் பகுப்பாய்வு செய்யுங்கள்",
    detectionResults: "AI கண்டறிதல் முடிவுகள்",
    detectedFruit: "கண்டறியப்பட்ட பழம்",
    category: "வகை",
    freshnessScore: "புத்துணர்ச்சி மதிப்பெண்",
    confirmListing: "உறுதிப்படுத்தி பட்டியலிடுங்கள்",
    yourListings: "உங்கள் பட்டியல்கள்",
    noListings: "இன்னும் பழங்கள் பட்டியலிடப்படவில்லை",
    recommendedUses: "பரிந்துரைக்கப்பட்ட பயன்பாடுகள்",
    faceMask: "முக மாஸ்க்",
    juice: "புதிய ஜூஸ்",
    smoothie: "ஸ்மூத்தி",
    cooking: "சமையல்",
    compost: "உரம்",
    purchaseSuccess: "வாங்குதல் வெற்றி!",
    grocerDetails: "விற்பனையாளர் விவரங்கள்",
    grocerName: "விற்பனையாளர் பெயர்",
    grocerPhone: "தொலைபேசி",
    grocerLocation: "பிக்கப் இடம்",
    pickupLocation: "பிக்கப் இடம்",
  },
  te: {
    back: "వెనుకకు",
    continue: "కొనసాగించు",
    confirm: "నిర్ధారించు",
    cancel: "రద్దు",
    loading: "లోడ్ అవుతోంది...",
    introTitle: "టెర్రాలూప్",
    introSubtitle: "తాజా పండ్లు, మాయాజాల అనుభవం",
    beginJourney: "మీ ప్రయాణాన్ని ప్రారంభించండి",
    selectLanguage: "భాషను ఎంచుకోండి",
    chooseLanguage: "మీ ఇష్టమైన భాషను ఎంచుకోండి",
    enterPhone: "మీ ఫోన్ నంబర్ నమోదు చేయండి",
    phoneNumber: "ఫోన్ నంబర్",
    sendOtp: "OTP పంపు",
    enterOtp: "OTP నమోదు చేయండి",
    verifyOtp: "OTP ధృవీకరించండి",
    resendOtp: "OTP మళ్ళీ పంపు",
    resendIn: "మళ్ళీ పంపు",
    enterName: "మీ పేరు నమోదు చేయండి",
    yourName: "మీ పేరు",
    welcomeUser: "స్వాగతం",
    chooseRole: "మీ మార్గాన్ని ఎంచుకోండి",
    roleQuestion: "మీరు కొనుగోలుదారా లేదా విక్రేతా?",
    buyer: "కొనుగోలుదారు",
    buyerDesc: "స్థానిక విక్రేతల నుండి తాజా పండ్లను కొనుగోలు చేయండి",
    grocer: "విక్రేత",
    grocerDesc: "మీ పండ్లను జాబితా చేయండి",
    xpEarned: "సంపాదించిన XP",
    level: "స్థాయి",
    chooseQuest: "మీ అన్వేషణను ఎంచుకోండి",
    selectProduce: "మీరు కోరుకునే పండ్ల రకాన్ని ఎంచుకోండి",
    climactericFruits: "క్లైమాక్టెరిక్ పండ్లు",
    climactericDesc: "పంట తర్వాత కూడా పక్వానికి వచ్చే పండ్లు",
    nonClimactericFruits: "నాన్-క్లైమాక్టెరిక్ పండ్లు",
    nonClimactericDesc: "పూర్తిగా పక్వమైన పండ్లు",
    browseCollection: "సేకరణను చూడండి",
    viewMarketplace: "మార్కెట్‌ప్లేస్‌లో చూడండి",
    addToCart: "కార్ట్‌కు జోడించు",
    buyNow: "ఇప్పుడు కొనండి",
    freshness: "తాజాదనం",
    shelfLife: "షెల్ఫ్ లైఫ్",
    price: "ధర",
    grocerGuild: "విక్రేత గిల్డ్",
    uploadPhotos: "4 ఫోటోలను అప్‌లోడ్ చేయండి",
    uploadDesc: "ఖచ్చితమైన AI విశ్లేషణ కోసం వివిధ కోణాల నుండి క్యాప్చర్ చేయండి",
    frontView: "ముందు వీక్షణ",
    sideView: "సైడ్ వీక్షణ",
    topView: "టాప్ వీక్షణ",
    closeUp: "క్లోజ్-అప్",
    analyzeAI: "AI తో విశ్లేషించండి",
    detectionResults: "AI గుర్తింపు ఫలితాలు",
    detectedFruit: "గుర్తించిన పండు",
    category: "వర్గం",
    freshnessScore: "తాజాదనం స్కోర్",
    confirmListing: "నిర్ధారించి జాబితా చేయండి",
    yourListings: "మీ జాబితాలు",
    noListings: "ఇంకా పండ్లు జాబితా చేయలేదు",
    recommendedUses: "సిఫార్సు చేసిన ఉపయోగాలు",
    faceMask: "ఫేస్ మాస్క్",
    juice: "తాజా జ్యూస్",
    smoothie: "స్మూతీ",
    cooking: "వంట",
    compost: "కంపోస్ట్",
    purchaseSuccess: "కొనుగోలు విజయవంతం!",
    grocerDetails: "విక్రేత వివరాలు",
    grocerName: "విక్రేత పేరు",
    grocerPhone: "ఫోన్",
    grocerLocation: "పికప్ స్థానం",
    pickupLocation: "పికప్ స్థానం",
  },
  mr: {
    back: "मागे",
    continue: "पुढे जा",
    confirm: "पुष्टी करा",
    cancel: "रद्द करा",
    loading: "लोड होत आहे...",
    introTitle: "टेरालूप",
    introSubtitle: "ताजी फळे, जादुई अनुभव",
    beginJourney: "तुमचा प्रवास सुरू करा",
    selectLanguage: "भाषा निवडा",
    chooseLanguage: "तुमची आवडती भाषा निवडा",
    enterPhone: "तुमचा फोन नंबर टाका",
    phoneNumber: "फोन नंबर",
    sendOtp: "OTP पाठवा",
    enterOtp: "OTP टाका",
    verifyOtp: "OTP सत्यापित करा",
    resendOtp: "OTP पुन्हा पाठवा",
    resendIn: "पुन्हा पाठवा",
    enterName: "तुमचे नाव टाका",
    yourName: "तुमचे नाव",
    welcomeUser: "स्वागत आहे",
    chooseRole: "तुमचा मार्ग निवडा",
    roleQuestion: "तुम्ही खरेदीदार आहात की विक्रेता?",
    buyer: "खरेदीदार",
    buyerDesc: "स्थानिक विक्रेत्यांकडून ताजी फळे खरेदी करा",
    grocer: "विक्रेता",
    grocerDesc: "तुमची फळे सूचीबद्ध करा",
    xpEarned: "मिळवलेले XP",
    level: "स्तर",
    chooseQuest: "तुमचा शोध निवडा",
    selectProduce: "तुम्हाला हवे असलेले फळ प्रकार निवडा",
    climactericFruits: "क्लायमेक्टेरिक फळे",
    climactericDesc: "कापणीनंतरही पिकणारी फळे",
    nonClimactericFruits: "नॉन-क्लायमेक्टेरिक फळे",
    nonClimactericDesc: "पूर्ण पिकलेली फळे",
    browseCollection: "संग्रह पहा",
    viewMarketplace: "मार्केटप्लेसमध्ये पहा",
    addToCart: "कार्टमध्ये जोडा",
    buyNow: "आता खरेदी करा",
    freshness: "ताजेपणा",
    shelfLife: "शेल्फ लाइफ",
    price: "किंमत",
    grocerGuild: "विक्रेता गिल्ड",
    uploadPhotos: "4 फोटो अपलोड करा",
    uploadDesc: "अचूक AI विश्लेषणासाठी वेगवेगळ्या कोनातून कॅप्चर करा",
    frontView: "समोरचे दृश्य",
    sideView: "बाजूचे दृश्य",
    topView: "वरचे दृश्य",
    closeUp: "क्लोज-अप",
    analyzeAI: "AI ने विश्लेषण करा",
    detectionResults: "AI शोध निकाल",
    detectedFruit: "ओळखलेले फळ",
    category: "श्रेणी",
    freshnessScore: "ताजेपणा स्कोर",
    confirmListing: "पुष्टी करा आणि सूचीबद्ध करा",
    yourListings: "तुमच्या सूची",
    noListings: "अजून फळे सूचीबद्ध नाहीत",
    recommendedUses: "शिफारस केलेले उपयोग",
    faceMask: "फेस मास्क",
    juice: "ताजा रस",
    smoothie: "स्मूदी",
    cooking: "स्वयंपाक",
    compost: "खत",
    purchaseSuccess: "खरेदी यशस्वी!",
    grocerDetails: "विक्रेता तपशील",
    grocerName: "विक्रेत्याचे नाव",
    grocerPhone: "फोन",
    grocerLocation: "पिकअप स्थान",
    pickupLocation: "पिकअप स्थान",
  },
  kn: {
    back: "ಹಿಂದೆ",
    continue: "ಮುಂದುವರಿಸು",
    confirm: "ದೃಢೀಕರಿಸು",
    cancel: "ರದ್ದು",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    introTitle: "ಟೆರಾಲೂಪ್",
    introSubtitle: "ತಾಜಾ ಹಣ್ಣುಗಳು, ಮಾಯಾ ಅನುಭವ",
    beginJourney: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    selectLanguage: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    chooseLanguage: "ನಿಮ್ಮ ಆಯ್ಕೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    enterPhone: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
    sendOtp: "OTP ಕಳುಹಿಸು",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    verifyOtp: "OTP ಪರಿಶೀಲಿಸಿ",
    resendOtp: "OTP ಮರುಕಳುಹಿಸು",
    resendIn: "ಮರುಕಳುಹಿಸು",
    enterName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    welcomeUser: "ಸ್ವಾಗತ",
    chooseRole: "ನಿಮ್ಮ ಮಾರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    roleQuestion: "ನೀವು ಖರೀದಿದಾರರಾ ಅಥವಾ ಮಾರಾಟಗಾರರಾ?",
    buyer: "ಖರೀದಿದಾರ",
    buyerDesc: "ಸ್ಥಳೀಯ ಮಾರಾಟಗಾರರಿಂದ ತಾಜಾ ಹಣ್ಣುಗಳನ್ನು ಖರೀದಿಸಿ",
    grocer: "ಮಾರಾಟಗಾರ",
    grocerDesc: "ನಿಮ್ಮ ಹಣ್ಣುಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ",
    xpEarned: "ಗಳಿಸಿದ XP",
    level: "ಹಂತ",
    chooseQuest: "ನಿಮ್ಮ ಅನ್ವೇಷಣೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    selectProduce: "ನೀವು ಹುಡುಕುತ್ತಿರುವ ಹಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    climactericFruits: "ಕ್ಲೈಮ್ಯಾಕ್ಟರಿಕ್ ಹಣ್ಣುಗಳು",
    climactericDesc: "ಕೊಯ್ಲಿನ ನಂತರವೂ ಹಣ್ಣಾಗುವ ಹಣ್ಣುಗಳು",
    nonClimactericFruits: "ನಾನ್-ಕ್ಲೈಮ್ಯಾಕ್ಟರಿಕ್ ಹಣ್ಣುಗಳು",
    nonClimactericDesc: "ಸಂಪೂರ್ಣ ಹಣ್ಣಾದ ಹಣ್ಣುಗಳು",
    browseCollection: "ಸಂಗ್ರಹವನ್ನು ನೋಡಿ",
    viewMarketplace: "ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ನೋಡಿ",
    addToCart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸು",
    buyNow: "ಈಗ ಖರೀದಿಸಿ",
    freshness: "ತಾಜಾತನ",
    shelfLife: "ಶೆಲ್ಫ್ ಲೈಫ್",
    price: "ಬೆಲೆ",
    grocerGuild: "ಮಾರಾಟಗಾರ ಗಿಲ್ಡ್",
    uploadPhotos: "4 ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadDesc: "ನಿಖರವಾದ AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ವಿವಿಧ ಕೋನಗಳಿಂದ ಸೆರೆಹಿಡಿಯಿರಿ",
    frontView: "ಮುಂಭಾಗದ ನೋಟ",
    sideView: "ಸೈಡ್ ನೋಟ",
    topView: "ಮೇಲಿನ ನೋಟ",
    closeUp: "ಕ್ಲೋಸ್-ಅಪ್",
    analyzeAI: "AI ಯೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ",
    detectionResults: "AI ಪತ್ತೆ ಫಲಿತಾಂಶಗಳು",
    detectedFruit: "ಪತ್ತೆಯಾದ ಹಣ್ಣು",
    category: "ವರ್ಗ",
    freshnessScore: "ತಾಜಾತನ ಸ್ಕೋರ್",
    confirmListing: "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಪಟ್ಟಿ ಮಾಡಿ",
    yourListings: "ನಿಮ್ಮ ಪಟ್ಟಿಗಳು",
    noListings: "ಇನ್ನೂ ಹಣ್ಣುಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ",
    recommendedUses: "ಶಿಫಾರಸು ಮಾಡಿದ ಬಳಕೆಗಳು",
    faceMask: "ಫೇಸ್ ಮಾಸ್ಕ್",
    juice: "ತಾಜಾ ಜ್ಯೂಸ್",
    smoothie: "ಸ್ಮೂದಿ",
    cooking: "ಅಡುಗೆ",
    compost: "ಕಾಂಪೋಸ್ಟ್",
    purchaseSuccess: "ಖರೀದಿ ಯಶಸ್ವಿ!",
    grocerDetails: "ಮಾರಾಟಗಾರರ ವಿವರಗಳು",
    grocerName: "ಮಾರಾಟಗಾರರ ಹೆಸರು",
    grocerPhone: "ಫೋನ್",
    grocerLocation: "ಪಿಕಪ್ ಸ್ಥಳ",
    pickupLocation: "ಪಿಕಪ್ ಸ್ಥಳ",
  },
  ml: {
    back: "പിന്നോട്ട്",
    continue: "തുടരുക",
    confirm: "സ്ഥിരീകരിക്കുക",
    cancel: "റദ്ദാക്കുക",
    loading: "ലോഡ് ചെയ്യുന്നു...",
    introTitle: "ടെറാലൂപ്",
    introSubtitle: "പുതിയ പഴങ്ങൾ, മാജിക്കൽ അനുഭവം",
    beginJourney: "നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    chooseLanguage: "നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    enterPhone: "നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക",
    phoneNumber: "ഫോൺ നമ്പർ",
    sendOtp: "OTP അയയ്ക്കുക",
    enterOtp: "OTP നൽകുക",
    verifyOtp: "OTP പരിശോധിക്കുക",
    resendOtp: "OTP വീണ്ടും അയയ്ക്കുക",
    resendIn: "വീണ്ടും അയയ്ക്കുക",
    enterName: "നിങ്ങളുടെ പേര് നൽകുക",
    yourName: "നിങ്ങളുടെ പേര്",
    welcomeUser: "സ്വാഗതം",
    chooseRole: "നിങ്ങളുടെ വഴി തിരഞ്ഞെടുക്കുക",
    roleQuestion: "നിങ്ങൾ വാങ്ങുന്നയാളാണോ വിൽക്കുന്നയാളാണോ?",
    buyer: "വാങ്ങുന്നയാൾ",
    buyerDesc: "പ്രാദേശിക വിൽപ്പനക്കാരിൽ നിന്ന് പുതിയ പഴങ്ങൾ വാങ്ങുക",
    grocer: "വിൽക്കുന്നയാൾ",
    grocerDesc: "നിങ്ങളുടെ പഴങ്ങൾ ലിസ്റ്റ് ചെയ്യുക",
    xpEarned: "നേടിയ XP",
    level: "ലെവൽ",
    chooseQuest: "നിങ്ങളുടെ തിരയൽ തിരഞ്ഞെടുക്കുക",
    selectProduce: "നിങ്ങൾ തിരയുന്ന പഴ തരം തിരഞ്ഞെടുക്കുക",
    climactericFruits: "ക്ലൈമാക്ടെറിക് പഴങ്ങൾ",
    climactericDesc: "വിളവെടുപ്പിനു ശേഷവും പാകമാകുന്ന പഴങ്ങൾ",
    nonClimactericFruits: "നോൺ-ക്ലൈമാക്ടെറിക് പഴങ്ങൾ",
    nonClimactericDesc: "പൂർണ്ണമായി പാകമായ പഴങ്ങൾ",
    browseCollection: "ശേഖരം കാണുക",
    viewMarketplace: "മാർക്കറ്റ്പ്ലേസിൽ കാണുക",
    addToCart: "കാർട്ടിലേക്ക് ചേർക്കുക",
    buyNow: "ഇപ്പോൾ വാങ്ങുക",
    freshness: "പുതുമ",
    shelfLife: "ഷെൽഫ് ലൈഫ്",
    price: "വില",
    grocerGuild: "വിൽപ്പനക്കാരുടെ ഗിൽഡ്",
    uploadPhotos: "4 ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക",
    uploadDesc: "കൃത്യമായ AI വിശകലനത്തിനായി വ്യത്യസ്ത കോണുകളിൽ നിന്ന് ക്യാപ്ചർ ചെയ്യുക",
    frontView: "മുൻ കാഴ്ച",
    sideView: "സൈഡ് കാഴ്ച",
    topView: "ടോപ്പ് കാഴ്ച",
    closeUp: "ക്ലോസ്-അപ്",
    analyzeAI: "AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുക",
    detectionResults: "AI കണ്ടെത്തൽ ഫലങ്ങൾ",
    detectedFruit: "കണ്ടെത്തിയ പഴം",
    category: "വിഭാഗം",
    freshnessScore: "പുതുമ സ്കോർ",
    confirmListing: "സ്ഥിരീകരിച്ച് ലിസ്റ്റ് ചെയ്യുക",
    yourListings: "നിങ്ങളുടെ ലിസ്റ്റിംഗുകൾ",
    noListings: "ഇതുവരെ പഴങ്ങൾ ലിസ്റ്റ് ചെയ്തിട്ടില്ല",
    recommendedUses: "ശുപാർശ ചെയ്ത ഉപയോഗങ്ങൾ",
    faceMask: "ഫേസ് മാസ്ക്",
    juice: "പുതിയ ജ്യൂസ്",
    smoothie: "സ്മൂത്തി",
    cooking: "പാചകം",
    compost: "കമ്പോസ്റ്റ്",
    purchaseSuccess: "വാങ്ങൽ വിജയകരം!",
    grocerDetails: "വിൽപ്പനക്കാരന്റെ വിശദാംശങ്ങൾ",
    grocerName: "വിൽപ്പനക്കാരന്റെ പേര്",
    grocerPhone: "ഫോൺ",
    grocerLocation: "പിക്കപ്പ് ലൊക്കേഷൻ",
    pickupLocation: "പിക്കപ്പ് ലൊക്കേഷൻ",
  },
  pa: {
    back: "ਪਿੱਛੇ",
    continue: "ਜਾਰੀ ਰੱਖੋ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    introTitle: "ਟੈਰਾਲੂਪ",
    introSubtitle: "ਤਾਜ਼ੇ ਫਲ, ਜਾਦੂਈ ਤਜਰਬਾ",
    beginJourney: "ਆਪਣਾ ਸਫ਼ਰ ਸ਼ੁਰੂ ਕਰੋ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    chooseLanguage: "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ",
    enterPhone: "ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    phoneNumber: "ਫ਼ੋਨ ਨੰਬਰ",
    sendOtp: "OTP ਭੇਜੋ",
    enterOtp: "OTP ਦਰਜ ਕਰੋ",
    verifyOtp: "OTP ਤਸਦੀਕ ਕਰੋ",
    resendOtp: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
    resendIn: "ਦੁਬਾਰਾ ਭੇਜੋ",
    enterName: "ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    yourName: "ਤੁਹਾਡਾ ਨਾਮ",
    welcomeUser: "ਸੁਆਗਤ ਹੈ",
    chooseRole: "ਆਪਣਾ ਰਾਹ ਚੁਣੋ",
    roleQuestion: "ਤੁਸੀਂ ਖਰੀਦਦਾਰ ਹੋ ਜਾਂ ਵੇਚਣ ਵਾਲੇ?",
    buyer: "ਖਰੀਦਦਾਰ",
    buyerDesc: "ਸਥਾਨਕ ਵੇਚਣ ਵਾਲਿਆਂ ਤੋਂ ਤਾਜ਼ੇ ਫਲ ਖਰੀਦੋ",
    grocer: "ਵੇਚਣ ਵਾਲਾ",
    grocerDesc: "ਆਪਣੇ ਫਲਾਂ ਨੂੰ ਸੂਚੀਬੱਧ ਕਰੋ",
    xpEarned: "ਕਮਾਇਆ XP",
    level: "ਪੱਧਰ",
    chooseQuest: "ਆਪਣੀ ਖੋਜ ਚੁਣੋ",
    selectProduce: "ਤੁਸੀਂ ਜੋ ਫਲ ਚਾਹੁੰਦੇ ਹੋ ਉਹ ਕਿਸਮ ਚੁਣੋ",
    climactericFruits: "ਕਲਾਈਮੈਕਟੈਰਿਕ ਫਲ",
    climactericDesc: "ਫਲ ਜੋ ਵਾਢੀ ਤੋਂ ਬਾਅਦ ਵੀ ਪੱਕਦੇ ਰਹਿੰਦੇ ਹਨ",
    nonClimactericFruits: "ਨਾਨ-ਕਲਾਈਮੈਕਟੈਰਿਕ ਫਲ",
    nonClimactericDesc: "ਪੂਰੀ ਤਰ੍ਹਾਂ ਪੱਕੇ ਹੋਏ ਫਲ",
    browseCollection: "ਸੰਗ੍ਰਹਿ ਦੇਖੋ",
    viewMarketplace: "ਮਾਰਕੀਟਪਲੇਸ ਵਿੱਚ ਦੇਖੋ",
    addToCart: "ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    buyNow: "ਹੁਣੇ ਖਰੀਦੋ",
    freshness: "ਤਾਜ਼ਗੀ",
    shelfLife: "ਸ਼ੈਲਫ਼ ਲਾਈਫ਼",
    price: "ਕੀਮਤ",
    grocerGuild: "ਵੇਚਣ ਵਾਲਿਆਂ ਦੀ ਗਿਲਡ",
    uploadPhotos: "4 ਫ਼ੋਟੋਆਂ ਅੱਪਲੋਡ ਕਰੋ",
    uploadDesc: "ਸਹੀ AI ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਵੱਖ-ਵੱਖ ਕੋਣਾਂ ਤੋਂ ਕੈਪਚਰ ਕਰੋ",
    frontView: "ਸਾਹਮਣੇ ਦਾ ਦ੍ਰਿਸ਼",
    sideView: "ਪਾਸੇ ਦਾ ਦ੍ਰਿਸ਼",
    topView: "ਉੱਪਰ ਦਾ ਦ੍ਰਿਸ਼",
    closeUp: "ਕਲੋਜ਼-ਅੱਪ",
    analyzeAI: "AI ਨਾਲ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    detectionResults: "AI ਖੋਜ ਨਤੀਜੇ",
    detectedFruit: "ਖੋਜਿਆ ਗਿਆ ਫਲ",
    category: "ਸ਼੍ਰੇਣੀ",
    freshnessScore: "ਤਾਜ਼ਗੀ ਸਕੋਰ",
    confirmListing: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਸੂਚੀਬੱਧ ਕਰੋ",
    yourListings: "ਤੁਹਾਡੀਆਂ ਸੂਚੀਆਂ",
    noListings: "ਅਜੇ ਤੱਕ ਕੋਈ ਫਲ ਸੂਚੀਬੱਧ ਨਹੀਂ ਹਨ",
    recommendedUses: "ਸਿਫ਼ਾਰਸ਼ੀ ਵਰਤੋਂ",
    faceMask: "ਫੇਸ ਮਾਸਕ",
    juice: "ਤਾਜ਼ਾ ਜੂਸ",
    smoothie: "ਸਮੂਦੀ",
    cooking: "ਖਾਣਾ ਬਣਾਉਣਾ",
    compost: "ਖਾਦ",
    purchaseSuccess: "ਖਰੀਦ ਸਫਲ!",
    grocerDetails: "ਵੇਚਣ ਵਾਲੇ ਦੇ ਵੇਰਵੇ",
    grocerName: "ਵੇਚਣ ਵਾਲੇ ਦਾ ਨਾਮ",
    grocerPhone: "ਫ਼ੋਨ",
    grocerLocation: "ਪਿੱਕਅੱਪ ਸਥਾਨ",
    pickupLocation: "ਪਿੱਕਅੱਪ ਸਥਾਨ",
  },
}

export function getTranslation(lang: Language): TranslationKeys {
  return translations[lang] || translations.en
}

export function useLocalization() {
  if (typeof window === "undefined") {
    return { t: translations.en, lang: "en" as Language }
  }
  
  const savedLang = localStorage.getItem("terraloop_language") as Language | null
  const lang = savedLang || "en"
  return { t: getTranslation(lang), lang }
}
